name: 'Setup AWS'
description: 'Setup combined actions for using AWS'

inputs:
  aws-access-key-id:
    required: true
  aws-secret-access-key:
    required: true
  aws-region:
    default: us-east-1
    required: true
  ecr-repository:
    description: 'Repository name to use (or create if it doesnt exist)'
    default: ''
  ca-domain:
    description: 'CodeArtifact domain. Leave blank to avoid setting up CodeArtifact'
    default: ''
  ca-domain-owner:
    description: 'CodeArtifact domain-owner'
  ca-repository:
    description: 'CodeArtifact repository'

outputs:
  ecr-registry:
    description: 'The URI of the ECR registry i.e. aws_account_id.dkr.ecr.region.amazonaws.com'
    value: ${{ steps.login-ecr.outputs.registry }}

runs:
  using: 'composite'
  steps:
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ inputs.aws-access-key-id }}
        aws-secret-access-key: ${{ inputs.aws-secret-access-key }}
        aws-region: ${{ inputs.aws-region }}

    - if: ${{ inputs.ecr-repository }}
      name: Login to ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - if: ${{ inputs.ecr-repository }}
      shell: bash
      run: aws ecr describe-repositories --repository-names '${{ inputs.ecr-repository }}' || aws ecr create-repository --repository-name '${{ inputs.ecr-repository }}'

    - if: ${{ inputs.ca-domain != '' }}
      name: "Setup CodeArtifact"
      uses: soluciones-algoritmicas/setup-codeartifact@v1
      with:
        domain: ${{ inputs.ca-domain }}
        domain-owner: ${{ inputs.ca-domain-owner }}
        region: ${{ inputs.aws-region }}
        repository: ${{ inputs.ca-repository }}